// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLkPz_Vu0m_EgwV1DmIBFzfNPxW7kV4V8',
    appId: '1:939017922505:web:f455ff65ad6cc1167a6a18',
    messagingSenderId: '939017922505',
    projectId: 'prueba-odasys',
    authDomain: 'prueba-odasys.firebaseapp.com',
    storageBucket: 'prueba-odasys.firebasestorage.app',
    measurementId: 'G-96M3G1XZW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNSOObpnq5pgYQnwJil4DxqpTvHcLhBM',
    appId: '1:939017922505:android:1ea128ed3f4e34237a6a18',
    messagingSenderId: '939017922505',
    projectId: 'prueba-odasys',
    storageBucket: 'prueba-odasys.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5aaZM8xzfSYb86p7xciftYDA81M7Pj3s',
    appId: '1:939017922505:ios:dc2808339c893c387a6a18',
    messagingSenderId: '939017922505',
    projectId: 'prueba-odasys',
    storageBucket: 'prueba-odasys.firebasestorage.app',
    iosBundleId: 'com.example.vinculedApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5aaZM8xzfSYb86p7xciftYDA81M7Pj3s',
    appId: '1:939017922505:ios:dc2808339c893c387a6a18',
    messagingSenderId: '939017922505',
    projectId: 'prueba-odasys',
    storageBucket: 'prueba-odasys.firebasestorage.app',
    iosBundleId: 'com.example.vinculedApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLkPz_Vu0m_EgwV1DmIBFzfNPxW7kV4V8',
    appId: '1:939017922505:web:d871618ba83af21a7a6a18',
    messagingSenderId: '939017922505',
    projectId: 'prueba-odasys',
    authDomain: 'prueba-odasys.firebaseapp.com',
    storageBucket: 'prueba-odasys.firebasestorage.app',
    measurementId: 'G-MERD85NBSE',
  );
}