// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfPnmd4ROCTW69-mS9Oww6rftk5KusF38',
    appId: '1:570377189463:web:75f6dfc4faa117fe290b12',
    messagingSenderId: '570377189463',
    projectId: 'odatalent-578e1',
    authDomain: 'odatalent-578e1.firebaseapp.com',
    storageBucket: 'odatalent-578e1.firebasestorage.app',
    measurementId: 'G-FYHWV93G35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ37sOnSdvvkFpFIfwB3Kgz-LBclTBlzs',
    appId: '1:570377189463:android:ef8612a696eb273d290b12',
    messagingSenderId: '570377189463',
    projectId: 'odatalent-578e1',
    storageBucket: 'odatalent-578e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuLeCILzvlNrZLfBrgxa4f5-QZhZ6p5U',
    appId: '1:570377189463:ios:09ca50e20185361d290b12',
    messagingSenderId: '570377189463',
    projectId: 'odatalent-578e1',
    storageBucket: 'odatalent-578e1.firebasestorage.app',
    iosBundleId: 'com.example.vinculedApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuLeCILzvlNrZLfBrgxa4f5-QZhZ6p5U',
    appId: '1:570377189463:ios:09ca50e20185361d290b12',
    messagingSenderId: '570377189463',
    projectId: 'odatalent-578e1',
    storageBucket: 'odatalent-578e1.firebasestorage.app',
    iosBundleId: 'com.example.vinculedApp1',
  );
}
