# Flutter iOS Podfile
platform :ios, '13.0'

# Si tu Mac es Apple Silicon y luego ves errores de 'arm64' en simulador,
# descomenta la línea siguiente:
# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#     end
#   end
# end

